on:
  repository_dispatch:
    types: [my-event]

env:
  AZURE_WEBAPP_NAME: ${{ github.event.client_payload.appname }}    # set this to your application's name
  SRCREGISTRY: ghcr.io
  DSTREGISTRY: app1acr.azurecr.io
  IMAGE_NAME: ${{ github.event.client_payload.imagename }}
  IMAGE_TAG: ${{ github.event.client_payload.imagetag }}

permissions:
  contents: read

jobs:
  sync-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.DSTREGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.SRCREGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        docker pull ${{ env.SRCREGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        docker tag ${{ env.SRCREGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.DSTREGISTRY }}/${{ genv.IMAGE_NAME }}:0.0.1-SNAPSHOT
        docker push ${{ env.DSTREGISTRY }}/${{ env.IMAGE_NAME }}:0.0.1-SNAPSHOT

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: sync-image

    steps:
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ env.DSTREGISTRY }}/${{ env.IMAGE_NAME }}:0.0.1-SNAPSHOT'
